# ワークフロー名
name: Manual
# イベント(プッシュ時に起動)
on: 
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
# ジョブの定義
jobs:
  # ジョブID
  run:
    # ランナー
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"